name: shopmart_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Scanner e OCR
  mobile_scanner: ^5.2.3
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.13.1

  # Chiamate API
  http: ^1.2.2

  # State management
  provider: ^6.1.2

  # Date formatting
  intl: ^0.20.2

  # Environment variables
  flutter_dotenv: ^5.2.1

  # PDF e condivisione
  pdf: ^3.11.1
  share_plus: ^10.1.2

  # Autenticazione
  google_sign_in: ^6.2.2
  flutter_secure_storage: ^9.2.2

  # Notifiche locali
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/

  # Fonts (aggiungi se vuoi)
  # fonts:
  #   - family: MyFont
  #     fonts:
  #       - asset: assets/fonts/MyFont-Regular.ttf

# Configurazione icone app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#5DADE2"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
